name: jak_one_pay
description: "Jak One Pay App."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  gradient_icon: ^2.0.9
  gradient_borders: ^1.0.0
  card_swiper: ^3.0.1
  velocity_x: ^4.1.2
  getwidget:
  flutter_localizations:
    sdk: flutter
#  intl: ^0.18.1
  provider: ^6.1.2
#  intl_utils: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/event/
    - assets/menu/
  generate: true
